checks:
  php: true
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - phpcs-run
    tests: true
filter:
  paths:
    - src/
  excluded_paths:
    - tests/
  dependency_paths:
    - src/Util/Ed25519.php